### ISSUE TITLE
Failed to decline updates

### ISSUE THREAD

**Issue by perfectly-preserved-pie** [bryandam/SoftwareUpdateScripts#39]
I'm getting these errors in the log. This is just one of many. 
It's been going on for a few months now, but last year the script was working just fine.
We're on CB 2010, Server 2016.

```
Declined update '2021-04 Cumulative Update for Windows 10 Version 1607 for x86-based Systems (KB5001347)' (ID: 4d8cb713-baf0-4208-a615-c716c56218cf). Source: Windows 10 Version: 1607
Failed to decline update '2021-04 Cumulative Update for Windows 10 Version 1607 for x86-based Systems (KB5001347)' (ID: 4d8cb713-baf0-4208-a615-c716c56218cf). Source: Windows 10 Version: 1607 Error: Could not find a part of the path 'C:\Users\guy\Desktop\dga\'..
Error: -2147024893): Could not find a part of the path 'C:\Users\guy\Desktop\dga\'.
At C:\Users\guy\Desktop\dga\Invoke-DGASoftwareUpdateMaintenance.ps1:1850 char:251
+ ... ,$Source" | Out-File $UpdateListOutputFile -Append -Encoding Default  ...+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

I don't understand why it can't find the path?

**Comment by bryand-recastsoftware** [comment]
Looks like you're specifying an invalid/inaccessible path for UpdateListOutputFile.

**Comment by shift-faced** [comment]
So these are the parameters I'm using:

`powershell.exe -ExecutionPolicy Bypass -File "C:\Users\guy\Desktop\dga\Invoke-DGASoftwareUpdateMaintenance.ps1" -CleanSources -CleanSUGs -RunCleanupWizard -Force -UseCustomIndexes -DeleteDeclined -DeclineSuperseded -DeclineByTitle @('*Preview*','*Beta*') -DeclineByPlugins `

Am I doing anything wrong there? I dunno where else I could be specifying UpdateListOutputFile. I've never even heard of that until I read through these errors.

**Comment by perfectly-preserved-pie** [comment]
Well, it's been working fine for the last two months. I dunno what changed but I'll close this issue out since there's nothing to do except blame it on gremlins.
