### ISSUE TITLE
Function call misspelling in v2.4

### ISSUE THREAD

**Issue by packerphil** [bryandam/SoftwareUpdateScripts#6]
The function 'Test-Exclusions' is misspelled when calling it in the v2.4 of the "Invoke-DGASoftwareUpdateMaintenance.ps1" script. Search for "Test-Exlusions" and replace with "Test-Exclusions" to fix it.

**Comment by bryandam** [comment]
Yea, I really really can't spell and need to get on board with VSCode to save me from myself.

**Comment by bryandam** [comment]
Thanks for finding those, just merged Chad's changes.  Still need to spend some time internally testing 2.4 before releasing ... for reasons just like this.
