### ISSUE TITLE
Feature request - Default UseCustomIndex

### ISSUE THREAD

**Issue by Skatterbrainz** [bryandam/SoftwareUpdateScripts#7]
If UseCustomIndex parameter is recommended (as a default) it should be enabled unless explicitly requested.  Maybe flip that around as -NoCustomIndex (switch param), so it runs by default unless the switch is invoked.

**Comment by ChadSimmons** [comment]
From my understanding, UseCustomIndex implements something that is highly needed but not supported by Microsoft.  So my default position is that it should be off unless specified, even if 99% of implementations enable it.  That being said, it really makes no difference to me which way it is implemented.

**Comment by Skatterbrainz** [comment]
That makes sense, but the verbiage should be updated to reflect that I think. Maybe the warning should be reworded or suppressed altogether?

**Comment by bryandam** [comment]
As Chad mentions, this is strictly not supported by MS although supposedly they do plan to add one of those indexes into the product.  So the only thing I'm adamant about is that the user has to take an active step to use them.  Since they're super helpful in first-run scenarios I put a not of it in the log file.

**Comment by Skatterbrainz** [comment]
I completely understand the rationale. And I realize this is nitpicky of me. But my OCD feels like it should either be disabled by default, or enabled with a gentle warning. If disabled, maybe it should say it's recommended, even though not supported. I'm just thinking of 2 incidents last year where Microsoft closed a support request because the customer used a utility which applied an unsupported method. Maybe this one isn't that serious and I'm being silly, which is always likely. Anyhow, just a thought. No worries.

**Comment by bryandam** [comment]
>If disabled, maybe it should say it's recommended, even though not supported
That's basically what it does.  It's disabled but warns you that you should use it.  When I release it I'll have documentation that will help users decide if they want to or not.

**Comment by ChadSimmons** [comment]
> Snark? 

I thought you were a snark and couldn't help it.  You can't exactly read your blog and think, man, this guy is one of the most straight-laced, stoic people around! ;)
