### ISSUE TITLE
config.ini has duplicate lines

### ISSUE THREAD

**Issue by Skatterbrainz** [bryandam/SoftwareUpdateScripts#8]
DeclineByPlugins appears twice the config.ini file - minor issue but just wanted to mention it.

**Comment by Skatterbrainz** [comment]
Edited file and submitted pull request

**Comment by Skatterbrainz** [comment]
Disregard.  I didn't see previous pull request.

**Comment by ChadSimmons** [comment]
FYI: I linked the pull request to the issue so it will atomically close when the pull request is merged... or at least that is the hope.  See https://guides.github.com/features/issues
